import { ArrowUpRight, Check, ChevronDown, Mail, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "../app/App";
import { Button } from "../components/ui/Button";
import { AppMockup } from "../components/ui/AppMockup";
import { heroImage, pageImages, categoryImages } from "../content/images";
import { usePageMeta } from "../hooks/usePageMeta";
type LeadRole = "artist" | "business";

type OpenLead = (role?: LeadRole) => void;
function Page({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { usePageMeta(title, description); return <main className="marketing-page">{children}</main>; }
function PageHero({ eyebrow, title, copy, image }: { eyebrow: string; title: string; copy: string; image?: { src: string; alt: string } }) { return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p></div>{image && <img src={image.src} alt={image.alt} />}</section>; }
function AppSection({ openLead }: { openLead: OpenLead }) { return <section className="app-section" id="app"><div><p className="eyebrow">THE NEXT CHAPTER</p><h2>The Cultgig app is coming soon.</h2><p>Discover creative talent. Find opportunities. Build meaningful connections.</p><div className="app-badges"><button disabled>App Store <small>Coming Soon</small></button><button disabled>Google Play <small>Coming Soon</small></button></div><Button variant="light" onClick={() => openLead()}>Get launch updates <ArrowUpRight size={16} /></Button></div><AppMockup /></section>; }
function ClosingCTA({ openLead }: { openLead: OpenLead }) { return <section className="closing-cta"><p className="eyebrow">THE FUTURE OF CREATIVE DISCOVERY</p><h2>Something better is being built.</h2><p>Join early and help shape the next chapter of creative work.</p><div><Button onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline" onClick={() => openLead("business")}>Get Early Access</Button></div></section>; }

export function HomePage({ openLead }: { openLead: OpenLead }) { return <Page title="The future of creative discovery" description="Cultgig is building a trusted space where artists and businesses can discover each other and build meaningful professional connections."><section className="home-hero"><img src={heroImage.src} alt={heroImage.alt} /><div className="home-hero-overlay" /><div className="home-hero-copy"><p className="eyebrow">THE FUTURE OF CREATIVE DISCOVERY</p><h1>A better way for artists and businesses to connect.</h1><p className="lede">Cultgig is building a trusted platform for discovering creative talent, creating opportunities, and building meaningful professional connections.</p><div><Button variant="light" onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline-light" onClick={() => openLead("business")}>Get Early Access</Button></div><small>Coming soon on iOS &amp; Android.</small></div><div className="hero-stamp"><span>CREATIVE TALENT</span><span>REAL OPPORTUNITIES</span><span>BETTER CONNECTIONS</span></div></section><section className="story-intro"><p className="eyebrow">WHAT IS CULTGIG?</p><h2>Creative work should be easier to discover.</h2><div><p>Artists have talent. Businesses have opportunities. But connecting the right people can still depend on scattered referrals, social media messages, personal networks, and endless searching.</p><p>Cultgig is being built to make that relationship simpler, more trusted, and more human.</p></div></section><section className="split-story"><img src={pageImages.aboutStory.src} alt={pageImages.aboutStory.alt} /><div><p className="eyebrow">THE PROBLEM</p><h2>Great work is everywhere. The right connection is harder to find.</h2><p>We are creating a calmer starting point for creative professionals and the people who want to work with them.</p><Link className="text-link" to="/about">Why Cultgig exists <ArrowUpRight size={16} /></Link></div></section><AudienceSection openLead={openLead} /><HowSection openLead={openLead} /><section className="categories-section"><p className="eyebrow">CREATIVE CULTURE</p><h2>A home for many ways to make an impact.</h2><div className="category-grid">{Object.values(categoryImages).map((image) => <article key={image.category} style={{ backgroundImage: `linear-gradient(0deg,#160f15cc,transparent),url(${image.src})` }}><strong>{image.category}</strong></article>)}</div></section><AppSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }

function AudienceSection({ openLead }: { openLead: OpenLead }) { return <section className="audience-section"><div className="section-heading"><p className="eyebrow">TWO SIDES. ONE ECOSYSTEM.</p><h2>One platform. Two sides. One creative ecosystem.</h2></div><div className="audience-grid"><article><span>FOR ARTISTS</span><h3>Turn your work into opportunity.</h3><p>Build your professional presence, showcase your skills, make your work easier to discover, and build credibility over time.</p><Button onClick={() => openLead("artist")}>Join as an Artist</Button></article><article><span>FOR BUSINESSES</span><h3>Find creative talent with confidence.</h3><p>Understand the work, find the right fit, and build professional relationships through the future Cultgig app.</p><Button onClick={() => openLead("business")}>Get Early Access</Button></article></div></section>; }
function HowSection({ openLead }: { openLead: OpenLead }) { const tracks = [{ title: "For Artists", steps: ["Create your presence", "Showcase your work", "Get discovered", "Connect with businesses"] }, { title: "For Businesses", steps: ["Discover creative talent", "Explore their work", "Find the right fit", "Connect and collaborate"] }]; return <section className="how-section"><div className="section-heading"><p className="eyebrow">INSIDE THE CULTGIG APP</p><h2>Designed around better introductions.</h2><p>These are the future product paths we are building toward.</p></div><div className="tracks">{tracks.map((track) => <article className="track" key={track.title}><h3>{track.title}</h3>{track.steps.map((step, index) => <div className="step" key={step}><b>{String(index + 1).padStart(2, "0")}</b><span>{step}</span></div>)}<Button variant="outline" onClick={() => openLead(track.title === "For Artists" ? "artist" : "business")}>{track.title === "For Artists" ? "Join as an Artist" : "Get Early Access"}</Button></article>)}</div></section>; }

export function HowItWorksPage({ openLead }: { openLead: OpenLead }) { return <Page title="How Cultgig works"><PageHero eyebrow="HOW IT WORKS" title="A clearer path to creative connection." copy="Cultgig is building a trusted space where creative professionals and businesses can discover each other, understand the work, and start better conversations." image={pageImages.howItWorksHero} /><HowSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }
export function AudiencePage({ kind, openLead }: { kind: "artist" | "business"; openLead: OpenLead }) { const artist = kind === "artist"; return <Page title={artist ? "For Artists" : "For Businesses"}><PageHero eyebrow={artist ? "FOR ARTISTS" : "FOR BUSINESSES"} title={artist ? "Your work deserves to be discovered." : "Better creative connections start here."} copy={artist ? "Your talent should not depend only on who you already know. Cultgig is being built to help your work travel further." : "Discovery can be fragmented across referrals, social messages, and endless searching. Cultgig is being built to make that process more trusted and straightforward."} image={artist ? pageImages.forArtistsHero : pageImages.forBusinessesHero} /><section className="feature-list"><p className="eyebrow">{artist ? "WHY CULTGIG" : "THE CULTGIG APPROACH"}</p>{(artist ? ["Your professional presence", "Showcase your work", "Discover opportunities", "Build your reputation"] : ["Discover", "Explore", "Understand", "Connect", "Collaborate"]).map((item, index) => <article key={item}><b>0{index + 1}</b><div><h2>{item}</h2><p>{artist ? ["Build a profile that represents your work and skills.", "Give businesses a better understanding of what you create.", "Find opportunities that match your creative direction.", "Create meaningful professional relationships over time."][index] : "A future product experience designed to help businesses move from curiosity to confident creative collaboration."}</p></div></article>)}</section><section className="simple-cta"><p>The Cultgig mobile app is coming soon.</p><Button onClick={() => openLead(artist ? "artist" : "business")}>{artist ? "Join as an Artist" : "Get Early Access"}</Button></section></Page>; }
export function AboutPage({ openLead }: { openLead: OpenLead }) { return <Page title="Why Cultgig exists"><PageHero eyebrow="ABOUT CULTGIG" title="Why Cultgig exists." copy="Creative talent is everywhere. Discovery is fragmented. We are building a better ecosystem for creative professionals and businesses." image={pageImages.aboutHero} /><section className="story-intro compact"><p className="eyebrow">OUR BELIEF</p><h2>Talent should be discovered through work, not just networks.</h2><p>We believe good introductions should hold space for craft, context, and the human story behind the work. The Cultgig mobile app will bring that vision to life.</p></section><ClosingCTA openLead={openLead} /></Page>; }

const questions = [{ q: "What is Cultgig?", a: "Cultgig is building a trusted ecosystem where artists and businesses can discover each other and build meaningful professional relationships." }, { q: "Who is Cultgig for?", a: "For artists, creative professionals, venues, brands, event teams, and businesses looking for better creative connections." }, { q: "How can artists join?", a: "Join the early-access list through the website. We will share launch updates as the mobile app gets closer." }, { q: "How can businesses join?", a: "Choose Get Early Access and share a few details so we can keep you informed." }, { q: "Is Cultgig currently available?", a: "The website is a marketing and early-access platform. The mobile app is coming soon." }, { q: "Can I book an artist through the website?", a: "No. The website does not support bookings. The Cultgig mobile app will provide the future product experience." }, { q: "Can I post a requirement through the website?", a: "No. The website does not support job or event posting. Businesses can join the early-access list." }, { q: "When is the app launching?", a: "The app is coming soon on iOS and Android. Join the list for launch updates." }];
export function FAQPage() { const [active, setActive] = useState<number | null>(null); return <Page title="Frequently Asked Questions"><PageHero eyebrow="FAQ" title="Good questions deserve clear answers." copy="A straightforward guide to what Cultgig is building, who it is for, and what happens next." /><section className="faq-list">{questions.map((item, index) => <article key={item.q}><button aria-expanded={active === index} onClick={() => setActive(active === index ? null : index)}><span>{item.q}</span><ChevronDown className={active === index ? "rotated" : ""} /></button>{active === index && <p>{item.a}</p>}</article>)}</section></Page>; }
export function ContactPage({ openLead }: { openLead: OpenLead }) { return <Page title="Contact Cultgig"><PageHero eyebrow="CONTACT" title="Let&apos;s start a better conversation." copy="For general questions, partnerships, artist interest, or business interest, reach out or join the early-access list." /><section className="contact-grid"><div><Mail size={22} /><h2>Say hello.</h2><p>We are listening to artists and businesses as Cultgig takes shape.</p>{siteEmail() && <a className="text-link" href={`mailto:${siteEmail()}`}>{siteEmail()} <ArrowUpRight size={16} /></a>}</div><div><Button onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline" onClick={() => openLead("business")}>Get Early Access</Button></div></section></Page>; }
function siteEmail() { return import.meta.env.VITE_SUPPORT_EMAIL || ""; }
export function LegalPage({ kind }: { kind: "Privacy Policy" | "Terms" }) { return <Page title={kind}><section className="legal-page"><p className="eyebrow">CULTGIG</p><h1>{kind}</h1><p>This page describes the policies that govern your use of the Cultgig website and information shared through the early-access forms.</p><h2>Information we collect</h2><p>We collect information you choose to share, such as your name, contact details, city, and interest in Cultgig. We use it to respond to questions and share relevant launch updates.</p><h2>Contact</h2><p>For questions about this page, please use the contact details configured for Cultgig.</p></section></Page>; }
export function NotFoundPage({ openLead }: { openLead: OpenLead }) { return <Page title="Page Not Found"><section className="not-found"><Sparkles /><h1>That page is still being imagined.</h1><p>Return home to explore what Cultgig is building.</p><Button onClick={() => openLead()}>Get Early Access</Button></section></Page>; }
