import { ArrowUpRight, Check, ChevronDown, Mail, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "../app/App";
import { Button } from "../components/ui/Button";
import { AppMockup } from "../components/ui/AppMockup";
import { heroImage, pageImages, categoryImages } from "../content/images";
import { usePageMeta } from "../hooks/usePageMeta";
type LeadRole = "artist" | "business";

type OpenLead = (role?: LeadRole) => void;
function Page({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { usePageMeta(title, description); return <main className="marketing-page">{children}</main>; }
function PageHero({ eyebrow, title, copy, image }: { eyebrow: string; title: string; copy: string; image?: { src: string; alt: string } }) { return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{copy}</p></div>{image && <img src={image.src} alt={image.alt} />}</section>; }
function AppSection({ openLead }: { openLead: OpenLead }) { return <section className="app-section" id="app"><div><p className="eyebrow">THE NEXT CHAPTER</p><h2>Something better is coming.</h2><p>The Cultgig app will bring artists and businesses closer, from discovering great work to starting meaningful conversations.</p><div className="app-badges"><button disabled>App Store <small>Coming Soon</small></button><button disabled>Google Play <small>Coming Soon</small></button></div><Button variant="light" onClick={() => openLead()}>Get launch updates <ArrowUpRight size={16} /></Button></div><AppMockup /></section>; }
function ClosingCTA({ openLead }: { openLead: OpenLead }) { return <section className="closing-cta"><p className="eyebrow">THE FUTURE OF CREATIVE DISCOVERY</p><h2>Something better is being built.</h2><p>Join early and help shape the next chapter of creative work.</p><div><Button onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline" onClick={() => openLead("business")}>Get Early Access</Button></div></section>; }

export function HomePage({ openLead }: { openLead: OpenLead }) { return <Page title="The future of creative discovery" description="Cultgig is building a trusted space where artists and businesses can discover each other and build meaningful professional connections."><section className="home-hero"><div className="home-hero-copy"><p className="eyebrow">THE FUTURE OF CREATIVE DISCOVERY</p><h1>Great creative work deserves to be discovered.</h1><p className="lede">Too much incredible talent still depends on who you know, where you live, or whether someone happens to see your work. Cultgig is building a better way for artists and businesses to find each other.</p><div><Button onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline" onClick={() => openLead("business")}>Get Early Access</Button></div><small>Coming soon on iOS &amp; Android.</small><p className="hero-micro-story">For the artist waiting for the right opportunity.<br />For the business trying to find the right talent.</p></div><div className="home-hero-visual"><img src={heroImage.src} alt={heroImage.alt} /><div className="hero-stamp"><span>CREATIVITY</span><span>OPPORTUNITY</span><span>CONNECTION</span></div></div></section><section className="story-intro"><p className="eyebrow">THE HUMAN TRUTH</p><h2>Talent is everywhere. Opportunity isn&apos;t always.</h2><div><p>Sometimes the hardest part isn&apos;t creating. It&apos;s getting seen. Sometimes you know exactly what you want, but not who to call.</p><p>That&apos;s the gap Cultgig is building to close.</p></div></section><section className="split-story"><img src={pageImages.aboutStory.src} alt={pageImages.aboutStory.alt} /><div><p className="eyebrow">THE CULTGIG IDEA</p><h2>Artists and businesses deserve a better way to find each other.</h2><p>We are creating a calmer starting point for creative professionals and the people who want to bring an idea to life.</p><Link className="text-link" to="/about">Why Cultgig exists <ArrowUpRight size={16} /></Link></div></section><AudienceSection openLead={openLead} /><HowSection openLead={openLead} /><WhySection /><section className="categories-section"><p className="eyebrow">THE CREATIVE WORLD</p><h2>Creativity doesn&apos;t fit into one category.</h2><div className="category-grid">{Object.values(categoryImages).map((image) => <article key={image.category} style={{ backgroundImage: `linear-gradient(0deg,#160f15cc,transparent),url(${image.src})` }}><strong>{image.category}</strong></article>)}</div></section><AppSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }

function AudienceSection({ openLead }: { openLead: OpenLead }) { return <section className="audience-section"><div className="section-heading"><p className="eyebrow">TWO SIDES. ONE ECOSYSTEM.</p><h2>One platform. Two sides. One creative ecosystem.</h2></div><div className="audience-grid"><article><span>FOR ARTISTS</span><h3>You&apos;ve spent years getting better at what you do.</h3><p>Your work should travel further than your personal network. Cultgig is being built to help artists present their work, tell their story, and become easier for the right businesses to discover.</p><Button onClick={() => openLead("artist")}>Join as an Artist</Button></article><article><span>FOR BUSINESSES</span><h3>Sometimes you know exactly what you want. You just don&apos;t know who to call.</h3><p>Whether you&apos;re planning a wedding, opening a venue, launching a brand, or creating an unforgettable event, finding the right creative person should feel easier.</p><Button onClick={() => openLead("business")}>Get Early Access</Button></article></div></section>; }
function HowSection({ openLead }: { openLead: OpenLead }) { const tracks = [{ title: "For Artists", steps: ["Tell your story", "Show your work", "Make your talent discoverable", "Build meaningful connections"] }, { title: "For Businesses", steps: ["Tell us what you're looking for", "Discover creative talent", "Explore their work", "Start the right conversation"] }]; return <section className="how-section"><div className="section-heading"><p className="eyebrow">INSIDE THE CULTGIG APP - COMING SOON</p><h2>Designed around better introductions.</h2><p>These are the future product paths we are building toward.</p></div><div className="tracks">{tracks.map((track) => <article className="track" key={track.title}><h3>{track.title}</h3>{track.steps.map((step, index) => <div className="step" key={step}><b>{String(index + 1).padStart(2, "0")}</b><span>{step}</span></div>)}<Button variant="outline" onClick={() => openLead(track.title === "For Artists" ? "artist" : "business")}>{track.title === "For Artists" ? "Join as an Artist" : "Get Early Access"}</Button></article>)}</div></section>; }
function WhySection() { const pillars = [["BE SEEN FOR YOUR WORK", "Your talent should speak louder than your network."], ["FIND THE RIGHT FIT", "Better discovery creates better matches."], ["BUILD TRUST", "People work better together when they understand who they're working with."], ["CREATE SOMETHING MEMORABLE", "The best events are remembered because they felt something."]]; return <section className="why-section"><div className="section-heading"><p className="eyebrow">WHY CULTGIG</p><h2>Make space for better creative work.</h2></div><div className="why-grid">{pillars.map(([title, copy], index) => <article key={title}><b>0{index + 1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section>; }

export function HowItWorksPage({ openLead }: { openLead: OpenLead }) { return <Page title="How Cultgig works"><PageHero eyebrow="HOW IT WORKS" title="A clearer path to creative connection." copy="Cultgig is building a trusted space where creative professionals and businesses can discover each other, understand the work, and start better conversations." image={pageImages.howItWorksHero} /><HowSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }
export function AudiencePage({ kind, openLead }: { kind: "artist" | "business"; openLead: OpenLead }) { const artist = kind === "artist"; const items = artist ? ["Your story", "Your work", "Your opportunities", "Your next chapter"] : ["Know what you're looking for.", "Discover people who fit.", "Understand their work.", "Connect directly.", "Create something memorable."]; const artistCopy = ["You're more than a category. Tell people what moves you and what you make.", "Show people what you're capable of. Give your work room to speak.", "Put your work where the right opportunities can find it.", "Build relationships that can take your work further."]; return <Page title={artist ? "For Artists" : "For Businesses"}><PageHero eyebrow={artist ? "FOR ARTISTS" : "FOR BUSINESSES"} title={artist ? "Your work deserves more than a scroll past." : "Great events start with the right people."} copy={artist ? "You've spent years learning your craft. Cultgig is being built to help the right people discover what you can do." : "Finding creative talent shouldn't mean scrolling through endless profiles, chasing referrals, or hoping someone replies."} image={artist ? pageImages.forArtistsHero : pageImages.forBusinessesHero} /><section className="feature-list"><p className="eyebrow">{artist ? "THE NEXT CHAPTER" : "COMING TO THE CULTGIG APP"}</p>{items.map((item, index) => <article key={item}><b>0{index + 1}</b><div><h2>{item}</h2><p>{artist ? artistCopy[index] : "A future product experience designed to help businesses move from a clear idea to the right creative conversation."}</p></div></article>)}</section><AppSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }
export function AboutPage({ openLead }: { openLead: OpenLead }) { return <Page title="Why Cultgig exists"><PageHero eyebrow="ABOUT CULTGIG" title="Why does finding the right creative person still feel harder than it should?" copy="Artists are building careers one project at a time. Businesses are building experiences one idea at a time. Somewhere between them is a gap." image={pageImages.aboutHero} /><section className="story-intro compact"><p className="eyebrow">THE GAP WE&apos;RE CLOSING</p><h2>Cultgig exists to bring both sides closer.</h2><p>We believe talent should be discovered through work, not just networks. The mobile app is the next chapter of that belief, built for artists, creative professionals, and businesses looking for a better way to find each other.</p></section><AppSection openLead={openLead} /><ClosingCTA openLead={openLead} /></Page>; }

const questions = [{ q: "What is Cultgig?", a: "Cultgig is building a trusted ecosystem where artists and businesses can discover each other and build meaningful professional relationships." }, { q: "Who is Cultgig for?", a: "For artists, creative professionals, venues, brands, event teams, and businesses looking for better creative connections." }, { q: "How can artists join?", a: "Join the early-access list through the website. We will share launch updates as the mobile app gets closer." }, { q: "How can businesses join?", a: "Choose Get Early Access and share a few details so we can keep you informed." }, { q: "Is Cultgig currently available?", a: "The website is a marketing and early-access platform. The mobile app is coming soon." }, { q: "Can I book an artist through the website?", a: "No. The website does not support bookings. The Cultgig mobile app will provide the future product experience." }, { q: "Can I post a requirement through the website?", a: "No. The website does not support job or event posting. Businesses can join the early-access list." }, { q: "When is the app launching?", a: "The app is coming soon on iOS and Android. Join the list for launch updates." }];
export function FAQPage() { const [active, setActive] = useState<number | null>(null); return <Page title="Frequently Asked Questions"><PageHero eyebrow="FAQ" title="Good questions deserve clear answers." copy="A straightforward guide to what Cultgig is building, who it is for, and what happens next." /><section className="faq-list">{questions.map((item, index) => <article key={item.q}><button aria-expanded={active === index} onClick={() => setActive(active === index ? null : index)}><span>{item.q}</span><ChevronDown className={active === index ? "rotated" : ""} /></button>{active === index && <p>{item.a}</p>}</article>)}</section></Page>; }
export function ContactPage({ openLead }: { openLead: OpenLead }) { return <Page title="Contact Cultgig"><PageHero eyebrow="CONTACT" title="Let's start a better conversation." copy="For general questions, partnerships, artist interest, or business interest, reach out or join the early-access list." /><section className="contact-grid"><div><Mail size={22} /><h2>Say hello.</h2><p>We are listening to artists and businesses as Cultgig takes shape.</p>{siteEmail() && <a className="text-link" href={`mailto:${siteEmail()}`}>{siteEmail()} <ArrowUpRight size={16} /></a>}</div><div><Button onClick={() => openLead("artist")}>Join as an Artist</Button><Button variant="outline" onClick={() => openLead("business")}>Get Early Access</Button></div></section></Page>; }
function siteEmail() { return import.meta.env.VITE_SUPPORT_EMAIL || ""; }
export function LegalPage({ kind }: { kind: "Privacy Policy" | "Terms" }) { return <Page title={kind}><section className="legal-page"><p className="eyebrow">CULTGIG</p><h1>{kind}</h1><p>This page describes the policies that govern your use of the Cultgig website and information shared through the early-access forms.</p><h2>Information we collect</h2><p>We collect information you choose to share, such as your name, contact details, city, and interest in Cultgig. We use it to respond to questions and share relevant launch updates.</p><h2>Contact</h2><p>For questions about this page, please use the contact details configured for Cultgig.</p></section></Page>; }
export function NotFoundPage({ openLead }: { openLead: OpenLead }) { return <Page title="Page Not Found"><section className="not-found"><Sparkles /><h1>That page is still being imagined.</h1><p>Return home to explore what Cultgig is building.</p><Button onClick={() => openLead()}>Get Early Access</Button></section></Page>; }
